FROM node:18-alpine

RUN apk add --no-cache icu-dev python3 make g++ && \
    adduser -D nodejs

USER nodejs
WORKDIR /home/nodejs

RUN npm install ircdjs && npm cache clean --force

EXPOSE 6667

CMD ["node", "/home/nodejs/node_modules/ircdjs/bin/ircd.js"]
